version: '3.8'

services:
  app:
    build: .
    ports:
      - '5050:5050'
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongo:27017/checkout
      - PORT=5050
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=checkout
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'db.runCommand({ ping: 1 }).ok' | mongosh localhost:27017/test --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
